# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image: 
  repository: harbor.demo.training.livew.io/livewyer-test/vote
  tag: 0.0.2

redis:
  usePassword: false

replicaCount: 1
